### ISSUE TITLE
General questions about the application

### ISSUE THREAD

**Issue by srikat** [mherrmann/Preview#2]
Is this meant for image files or any type of file incl. txt files?

Any suggestions for a viewer software on Windows?

**Comment by mherrmann** [comment]
You can configure any Previewer application you like. So the answer to your first question (images or also txt files) is: it depends on the Previewer application you pick. I'm sure many of them will support images, txt files etc.

I don't have specific recommendations, sorry.

**Comment by cja-github** [comment]
Ok, but you created the plugin, so surely you did so knowing there was a previewing application worth supporting...
