### ISSUE TITLE
Select a viewer

### ISSUE THREAD

**Issue by gralp-1** [mherrmann/Preview#3]
When I press f3, I get this 
![image](https://user-images.githubusercontent.com/62028969/115761358-2c646480-a39a-11eb-825d-91ee253734e4.png)

and it tells me to pick a viewer. I do not understand what this means

**Comment by mherrmann** [comment]
The viewer is an application that you can use to view or preview files. So when you press OK in the dialog and select the .exe file of a program you have installed, it will use that program to open (/view) the file you had selected in fman.

**Comment by cja-github** [comment]
Please can you suggest a previewing application?
